buildingo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('', include('user_profile.urls')),
    path('', include('verifikasi.urls')),
    path('', include('find_professional.urls')),
    path('', include('portfolio.urls')),
    path('',include('project.urls'))
]

find_professional/urls.py
from django.urls import path
from . import views

app_name = 'find_professional'

urlpatterns = [
    path('professionals/<str:type>/', views.professionals, name="professionals"),
    path('projectrequest/<str:name_id>/', views.projectrequest, name="projectrequest")
]

home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.home, name="home"),
]

user_profile/urls.py
from django.urls import path
from . import views

app_name = 'user_profile'

urlpatterns = [
    path('login', views.login, name='login'),
    path('logout', views.logout, name='logout'),
    path('signup', views.signup, name='signup'),
    path('profile', views.profile, name='myProfile'),
    path('profile/edit', views.edit_profile, name='editProfile'),
    path('profile/save', views.save_profile, name='saveProfile'),
    path('profile/verify', views.verify_profile, name='verifyProfile'),
    path('profile/<str:name>', views.profile_outside, name='profileProfessional'),
]

home/models.py
from django.db import models

# Create your models here.

home/views.py
from django.shortcuts import render
from django.contrib.sessions.models import Session

def home(request):
    context = {}
    try:
        context['role'] = request.session['role']
    except KeyError:
        request.session['role'] = ''
        context['role'] = request.session['role']

    return render(request, 'home/home.html', context)

home/templates/home/base.html
<!DOCTYPE html>
<html lang="en">
  {% load static %}
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    {% block title %}
    <!-- Your title goes here -->
    {% endblock %}

    <!-- Bootstrap -->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
      crossorigin="anonymous"
    />
  
    <script 
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" 
      integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" 
      crossorigin="anonymous">
    </script>
    <script
      src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
      integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
      integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
      integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
      crossorigin="anonymous"
    ></script>
    <link 
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" 
      rel="stylesheet" 
      integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" 
      crossorigin="anonymous"
    />
    <script 
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" 
      integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" 
      crossorigin="anonymous">
    </script>

    <!-- GoogleFonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <!-- Poppins -->
    <link
      href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap"
      rel="stylesheet"
    />
    <!-- Roboto -->
    <link
      href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap"
      rel="stylesheet"
    />

    <!-- CSS Files -->
    <link rel="stylesheet" href="{% static 'home/css/base.css' %}" />

    <!-- Font Awesome -->
    <script
      src="https://kit.fontawesome.com/a0a9f5dd6d.js"
      crossorigin="anonymous"
    ></script>

    {% block link %}
    <!-- Your CSS/JS Files goes here -->
    {% endblock %}
  </head>

  {% block base %}
  <body>
    <!-- Navbar -->
    <ul class="nav nav-base">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'home:home' %}">BUILDINGO</a>
      </li>
      <li class="nav-item nav-item-home dropdown">
        <a class="nav-link nav-link-home dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Find Professional
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{% url 'find_professional:professionals' type='Architect' %}">Architect</a>
          <a class="dropdown-item" href="{% url 'find_professional:professionals' type='Contractor' %}">Contractor</a>
          <a class="dropdown-item font-purple" href="{% url 'find_professional:professionals' type='All' %}">All Professional <i class="fas fa-angle-right"></i></a> 
        </div>
      </li>
      {% if role == 'Project Owner' or role == 'Administrator' or role == 'Professional' %}
      <li class="nav-item nav-item-home ms-auto">
        <a class="nav-link nav-link-home" href="{% url 'user_profile:myProfile' %}"> <i class="fas fa-tasks me-2"></i> Dashboard</a>
      </li>
      <li class="nav-item nav-item-home">
        <a class="nav-link nav-link-home" href="{% url 'user_profile:logout' %}"> <i class="fas fa-sign-out-alt fa-rotate-180 me-2"></i>Log Out</a>
      </li>
      {% else %}
      <li class="nav-item ms-auto">
        <a class="nav-link" href="{% url 'user_profile:signup' %}"> <i class="fas fa-user me-2"></i> Sign Up</a>
      </li>
      <li class="nav-item">
        <a class="nav-link login rounded" href="{% url 'user_profile:login' %}"> <i class="fas fa-sign-in-alt me-2"></i> Log In</a>
      </li>
      {% endif %}
    </ul>

    {% block body %}
    <!-- Your content goes here -->
    {% endblock %}

    {% block script %}
    <!-- Yout script goes here -->
    {% endblock %}
    
  </body>
  {% endblock %}

</html>

home/templates/home/home.html
{% extends 'home/base.html' %}
{% load static %}

{% block title %}
<title>BUILDINGO</title>
{% endblock %}

{% block link %} 
<link rel="stylesheet" href="{% static 'home/css/home.css' %}">
{% endblock %}

{% block base %}
<body>
<section class="main-header">
    <!-- Navbar only for home -->
    <ul class="nav nav-home">
        <li class="nav-item nav-item-home dropdown">
          <a class="nav-link nav-link-home dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Find Professional
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="{% url 'find_professional:professionals' type='Architect' %}">Architect</a>
            <a class="dropdown-item" href="{% url 'find_professional:professionals' type='Contractor' %}">Contractor</a>
            <a class="dropdown-item font-purple" href="{% url 'find_professional:professionals' type='All' %}">All Professional <i class="fas fa-angle-right"></i></a> 
          </div>
        </li>
        {% if role == 'Project Owner' or role == 'Administrator' or role == 'Professional' %}
        <li class="nav-item nav-item-home">
            <a class="nav-link nav-link-home" href="{% url 'user_profile:myProfile' %}">Dashboard</a>
          </li>
        
        {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'user_profile:signup' %}">  Sign Up</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'user_profile:login' %}">Log In</a>
        </li>
        {% endif %}
    </ul>
    
    <div class="title">
        <h1>BUILDINGO</h1>
        
        <h5>CONNECTING PROJECT OWNER WITH </h5>
        <h5>TRUSTED PROFESSIONAL: ARCHITECT & CONTRACTOR</h5>

        <!-- Langsung menuju Find Professional Default (All Professional) -->
        <a href="{% url 'find_professional:professionals' type='All' %}" type="button" class="btn-find-professional btn"> Find Professional</a>
    </div>
    
</section>
</body>

{% endblock %}