buildingo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('', include('user_profile.urls')),
    path('', include('verifikasi.urls')),
    path('', include('find_professional.urls')),
    path('', include('portfolio.urls')),
    path('',include('project.urls'))
]

find_professional/urls.py
from django.urls import path
from . import views

app_name = 'find_professional'

urlpatterns = [
    path('professionals/<str:type>/', views.professionals, name="professionals"),
    path('projectrequest/<str:name_id>/', views.projectrequest, name="projectrequest")
]

home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.home, name="home"),
]

user_profile/urls.py
from django.urls import path
from . import views

app_name = 'user_profile'

urlpatterns = [
    path('login', views.login, name='login'),
    path('logout', views.logout, name='logout'),
    path('signup', views.signup, name='signup'),
    path('profile', views.profile, name='myProfile'),
    path('profile/edit', views.edit_profile, name='editProfile'),
    path('profile/save', views.save_profile, name='saveProfile'),
    path('profile/verify', views.verify_profile, name='verifyProfile'),
    path('profile/<str:name>', views.profile_outside, name='profileProfessional'),
]

find_professional/models.py
from django.db import models

# Create your models here.

find_professional/views.py
from decimal import Context
from django.shortcuts import render, redirect
from .db import *

# Create your views here.

def professionals(request, type):
    role = request.session['role']
    if type == "All" :
        context = {
            'role': role,
            'professional_list': get_professional_all()
        }
    else :
        context = {
            'role': role,
            'professional_list': get_professional(type)
        }
    return render(request, 'find_professional/find_professional.html', context)

def projectrequest(request,name_id):
    if request.method == 'GET':
        professional_type = get_professional_type(name_id)
        with connection.cursor() as cursor :
            user_id = request.session['id']
            if professional_type[0][0] == "Architect" :
                cursor.execute(f"select id, title from project where owner_id = '{user_id}' and status='OPN' and type like '%Design%'")
                context = {
                    'professional_id' : name_id,
                    'professional_name' : get_professional_nama(name_id),
                    'project_list' : [{'id': row[0], 'title': row[1]} for row in cursor.fetchall()]
                }
            else :
                cursor.execute(f"select id, title from project where owner_id = '{user_id}' and status='OPN' and type like '%Construct%'")
                context = {
                    'professional_id' : name_id,
                    'professional_name' : get_professional_nama(name_id),
                    'project_list' : [{'id': row[0], 'title': row[1]} for row in cursor.fetchall()]
                }
            return render(request, 'find_professional/requestproject.html',context)

    elif request.method == 'POST':
        user_id = request.session['id']
        data = request.POST.dict()
        data.pop('csrfmiddlewaretoken')
        assign_project(data,name_id)
        # update_status_project(data, user_id)
        return redirect('project:projectList')
    

   

find_professional/templates/find_professional/find_professional.html
{% extends 'home/base.html' %}
{% load static %}

{% block title %}
<title>Find Professional</title>
{% endblock %}

{% block link %}

{% block style %}
<!-- Specific profile/project/portfolio styling goes here -->
<link rel="stylesheet" href="{% static 'find_professional/css/find_professional.css' %}">
{% endblock %}

{% endblock %}

{% block body %}
<section>
    <h4>Find Professional</h4>

    <div class="content-wrapper">
        {% block section %}
        <div class="row row-cols-1 row-cols-md-3 g-4">
          {% for professional in professional_list %}
            <div class="col">
              <div class="card h-100">
                    <div class="card-body">
                        <div class="d-flex">
                            <div class="flex-shrink-0">
                              <img class="rounded-circle img-fluid" src="/static/profile/images/{{professional.profpic}}" alt="Card Image">
                            </div>
                            <div class="flex-grow-1 ms-3">
                                <h5 class="card-title title"> {{professional.name}}</h5>
                                <p><i class="fas fa-map-marker-alt font-purple"></i>   {{professional.region}}</p>
                                <p><i class="fas fa-user-check font-purple"></i> {{professional.professional_type}}</p>
                            </div>
                          </div>
                      <div class="container-card-text">
                      <p class="card-text text">{{professional.about_me}}</p>
                      </div>
                      <a class="font-purple" href="{% url 'user_profile:profileProfessional' professional.name %}">Read More  <i class="fas fa-angle-right"></i></a>
                      <!-- Button trigger modal -->
                        {% if role == 'Project Owner' %}
                          <div class="btn-requests">
                            <a href="{% url 'find_professional:projectrequest' professional.id %}" class="btn btn-primary float-end">Request Project</a>
                          </div>
                        {% endif %}
                    </div>
              </div>
            </div>
            {% endfor %}
          </div>
        </div>
        {% endblock %}
      </section>
  {% endblock %}
            <!-- <div class="col">
              <div class="card h-100">
                  <img class="card-img-top img-fluid" src="/static/find_professional/images/megatika(1).jpg" alt="Card Image">
                    <div class="card-body">
                        <div class="d-flex">
                            <div class="flex-shrink-0">
                              <img class="rounded-circle img-fluid" src="/static/find_professional/images/megatika.jpg" alt="Card Image">
                            </div>
                            <div class="flex-grow-1 ms-3">
                                <h5 class="card-title title">PT Megatika Grahalestari Internasional</h5>
                                <p><i class="fas fa-map-marker-alt font-purple"></i>  Seoul, South Korea</p>
                                <p><i class="fas fa-user-check font-purple"></i> Architect</p>
                            </div>
                          </div>
                      <div class="container-card-text">
                      <p class="card-text text">PT Megatika Grahalestari Internasional was established in Jakarta at 1992. Our company offers a wide range of architecture services in design and planning, from concept design, development design to project supervision. With extensive experience in designing compact and high density buildings in Hong Kong, Mr. Herbert and Board of Directors have transformed PT Megatika into a sizeable architectural consultant firm designing highrise apartments, hotels, shopping malls, office towers, 
                                            real estates, and also school buildings and religious buildings as part of our corporate social responsibility.</p>
                      </div>
                      <a class="font-purple" href="#">Read More  <i class="fas fa-angle-right"></i></a>
                  
                        {% if role == 'Project Owner' %}
                        <div class="btn-requests">
                          <a href="#" class="btn btn-primary float-end" data-bs-toggle="modal" data-bs-target="#staticBackdrop">Request Project</a>
                        </div>
                        {% endif %}
                    </div>
              </div>
            </div> -->
            <!-- <div class="col">
              <div class="card h-100">
                <img class="card-img-top  img-fluid" src="/static/find_professional/images/YG.jpg" alt="Card Image">
                    <div class="card-body">
                        <div class="d-flex">
                            <div class="flex-shrink-0">
                              <img class="rounded-circle  img-fluid" src="/static/find_professional/images/yg-labels.jpg" alt="Card Image">
                            </div>
                            <div class="flex-grow-1 ms-3">
                                <h5 class="card-title title">YG Property</h5>
                                <p><i class="fas fa-map-marker-alt font-purple"></i>   Daejeon, South Korea</p>
                                <p><i class="fas fa-user-check font-purple"></i> Contractor</p>
                            </div>
                          </div>
                    <div class="container-card-text">
                    <p class="card-text text">Since 1979, YG PROPERTY has been building and managing vibrant, sustainable communities and developments where residents and businesses thrive. We have pioneered the creation of livable, integrated developments that combine aspirational homes, public amenities, commerce and transit. 
                                      We build lasting value, not only for this generation, but for those to come.</p>
                    </div>
                    <a class="font-purple" href="#">Read More  <i class="fas fa-angle-right"></i></a>
                 
                        {% if role == 'Project Owner' %}
                        <div class="btn-requests">
                          <a href="#" class="btn btn-primary float-end" data-bs-toggle="modal" data-bs-target="#staticBackdrop">Request Project</a>
                        </div>
                        {% endif %}
                    </div>
              </div>
            </div> -->
            <!-- <div class="col">
              <div class="card h-100">
                <div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="carousel" data-bs-touch="false" data-bs-interval="false">
                  <div class="carousel-indicators">
                      <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
                      <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1" aria-label="Slide 2"></button>
                      <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2" aria-label="Slide 3"></button>
                    </div>
                    <div class="carousel-inner">
                      <div class="carousel-item active">
                        <img class="w-100 img-fluid" src="/static/find_professional/images/hybe.jpg" alt="Card Image">
                      </div>
                      <div class="carousel-item">
                        <img class="w-100 img-fluid" src="/static/find_professional/images/hybe-interior(1).jpg" alt="Card Image">
                      </div>
                      <div class="carousel-item">
                        <img class="w-100 img-fluid" src="/static/find_professional/images/hybe-interior(3).jpg" alt="Card Image">
                      </div>
                    </div>
                    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
                      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                      <span class="visually-hidden">Previous</span>
                    </button>
                    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
                      <span class="carousel-control-next-icon" aria-hidden="true"></span>
                      <span class="visually-hidden">Next</span>
                    </button>
                  </div>
                    <div class="card-body">
                        <div class="d-flex">
                            <div class="flex-shrink-0">
                              <img class="rounded-circle img-fluid" src="/static/find_professional/images/hybe-labels.jpg" alt="Card Image">
                            </div>
                            <div class="flex-grow-1 ms-3">
                                <h5 class="card-title title">HYBE Corporation</h5>
                                <p><i class="fas fa-map-marker-alt font-purple"></i>  Gwangju, South Korea</p>
                                <p><i class="fas fa-user-check font-purple"></i> Contractor</p>
                            </div>
                        </div>
                        <div class="container-card-text">
                          <p class="card-text text">Architecten-Ingenicure-en Annemersbedrijf Associatie Selle en de Bruyn, Reyerse en de Vries NV (Assosiate NV) is a Dutch-owned company that became the forerunner of the establishment of ADHI until it was finally nationalized and then designated as PN Adhi Karya on March 11, 1960. This nationalization became a driver of infrastructure development in Indonesia. Based on the approval of the Minister of Justice of the Republic of Indonesia, on June 1, 1974, ADHI changed its status to a Limited Liability Company. 
                            By 2004 ADHI had become the first construction company listed on the Indonesia Stock Exchange.
                          </p>
                        </div>
                      <a class="font-purple" href="#">Read More  <i class="fas fa-angle-right"></i></a>
               
                        {% if role == 'Project Owner' %}
                        <div class="btn-requests">
                          <a href="#" class="btn btn-primary float-end" data-bs-toggle="modal" data-bs-target="#staticBackdrop">Request Project</a>
                        </div>
                        {% endif %}
                    </div>
              </div>
            </div> -->

            
        <!-- Modal
        <div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered" role="document">
                <div class="modal-content">
                    <div class="modal-header request">
                      <h3 class="modal-title" id="exampleModalCenterTitle">Request Project</h3>
                    </div>
                    <div class="modal-body">
                      <form>
                        <div class="mb-3">
                          <label for="exampleInputEmail1">Professional</label>
                          <input class="form-control" type="text" id="professionalname" aria-label="Disabled input example" disabled readonly>
                        </div>
                        <div class="mb-3">
                            <label for="validationCustom04" class="form-label">Project</label>
                            <select class="form-select" id="validationCustom04" required>
                              <option selected disabled value="">Choose Your Project</option>
                              <option>Project A</option>
                              <option>Project B</option>
                              <option>Project C</option>
                              <option>Project D</option>
                            </select>
                            <div class="invalid-feedback">
                              Please select a valid state.
                            </div>
                        </div>
                      </form>
                    </div>
                    <div class="modal-footer">
                    <a class="btn btn-primary" data-bs-dismiss="modal">Close</a>
                    <a class="btn btn-primary">Request</a>
                    </div>
                </div>
            </div>
        </div> -->

<!-- <script>
  $(document).ready(function() {
    $(document).on('click','#requestproject',function() {
      var professionalname = $(this).data('professionalname');
      $('#professionalname').val(professionalname);
    })
  })
</script> -->

find_professional/templates/find_professional/requestproject.html
{% extends 'home/base.html' %}
{% load static %}

{% block title %}
<title>Request Project</title>
{% endblock %}

{% block link %} 

{% block style %} 
<link rel="stylesheet" href="{% static 'find_professional/css/requestproject.css' %}">

{% endblock %}

{% endblock %}

{% block body %}

<section>
    <div class="content-wrapper">
        {% block section %}
        <div class="request-page">
            <a href="{% url 'find_professional:professionals' type='All' %}" class="btn"><i class="fas fa-chevron-left"></i> Back</a>
            <div class="request-form">
                <div class="request-form-header">
                    <h4>Request Project</h4>
                </div>
                <div class="request-form-content">
                    <form action="{% url 'find_professional:projectrequest' professional_id %}" method="POST">
                        {% csrf_token %}
                        <div class="mb-3">
                          <label for="exampleInputEmail1">Professional</label>
                          <input class="form-control" type="text" value="{{professional_name}}" name="namaprofessional" id="namaprofessional" disabled readonly>
                        </div>
                        <div class="mb-3">
                            <label for="validationCustom04" class="form-label">Project</label>
                            <select class="form-select" name="validationCustom04" id="validationCustom04" required>
                              <option selected disabled value="">Choose Your Project</option>
                              {% for project in project_list %}
                              <option value={{project.id}} data-project-title={{project.title}}>{{project.title}}</option>
                              {% endfor %}
                            </select>
                            <div class="invalid-feedback">
                              Please select a valid state.
                            </div>
                        </div>
                      <div class="d-grid gap-2 d-md-flex justify-content-md-end">
                        <a href="{% url 'find_professional:professionals' type='All' %}" class="btn btn-primary btn-request float-right">Cancel</a>
                        <button type="submit" class="btn btn-primary btn-request float-right submit" data-bs-toggle="modal" data-bs-target="#exampleModal">Request</button>
                      </div>
                    </form>
                </div>    
            </div>


        </div>
        <!-- Modal -->
        <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header request">
                <h3 class="modal-title" id="exampleModalCenterTitle">Request Project</h3>
              </div>
              <div class="modal-body">
                Request project to {{professional_name}} has succeeded.
              </div>
              <div class="modal-footer">
                <a href="{% url 'find_professional:professionals' type='All' %}" type="button" class="btn btn-primary btn-request" data-bs-dismiss="modal">Close</a>
              </div>
            </div>
          </div>
        </div>
        {% endblock %}
    </div>
</section>

{% endblock %}