buildingo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('', include('user_profile.urls')),
    path('', include('verifikasi.urls')),
    path('', include('find_professional.urls')),
    path('', include('portfolio.urls')),
    path('',include('project.urls'))
]

find_professional/urls.py
from django.urls import path
from . import views

app_name = 'find_professional'

urlpatterns = [
    path('professionals/<str:type>/', views.professionals, name="professionals"),
    path('projectrequest/<str:name_id>/', views.projectrequest, name="projectrequest")
]

home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.home, name="home"),
]

portfolio/urls.py
from django.urls import path
from . import views

app_name = 'portfolio'

urlpatterns = [
    path('portfolio', views.portfolio, name="portfolio"),
    path('portfolio/<str:name>', views.portfolioOutside, name='portfolioOutside'),
    path('portfolio/<str:name>/<str:id>/', views.detailPortfolioOutside, name='detailPortfolioOutside'),
    path('create-portfolio', views.createPortfolio, name="createPortfolio"),
    path('detail-portfolio/<str:id>/', views.detailPortfolio, name="detailPortfolio"),
    path('edit-portfolio/<str:id>/', views.editPortfolio, name="editPortfolio"),
    path('delete-portfolio/<str:id>/', views.deletePortfolio, name="deletePortfolio"),
]

project/urls.py
from os import name
from django.urls import path
from . import views

app_name = 'project'

urlpatterns = [
    path('project', views.project, name="projectList"),
    path('createProject',views.create_project,name="createProject"),
    path('editproject<str:edit_id>',views.edit_project,name="editproject"),
    path('projectdetail/<str:detail_id>',views.project_detail,name="projectDetail"),
    path('deleteproject/<str:delete_id>',views.delete_project,name="deleteproject"),
    path('cancelproject/<str:cancel_id>',views.cancellation_project,name="cancelproject"),
    path('filedownload/<path:filename>',views.pdf_download, name="download"),
    path('acceptproject/<str:project_id>',views.accept_project, name="acceptproject"),
    path('rejectproject/<str:project_id>',views.reject_project, name="rejectproject"),
    path('startproject/<str:project_id>',views.start_project,name="startproject")
]

user_profile/urls.py
from django.urls import path
from . import views

app_name = 'user_profile'

urlpatterns = [
    path('login', views.login, name='login'),
    path('logout', views.logout, name='logout'),
    path('signup', views.signup, name='signup'),
    path('profile', views.profile, name='myProfile'),
    path('profile/edit', views.edit_profile, name='editProfile'),
    path('profile/save', views.save_profile, name='saveProfile'),
    path('profile/verify', views.verify_profile, name='verifyProfile'),
    path('profile/<str:name>', views.profile_outside, name='profileProfessional'),
]

verifikasi/urls.py
from django.urls import path
from . import views

app_name = 'verifikasi'

urlpatterns = [
    path('verif/listProfessional', views.listProfessional, name='listProfessional'),
    path('verif/listProject', views.listProject, name='listProject'),
    path('verif/detailProject/<str:id>', views.detailProject, name='detailProject'),
    path('verif/detailProfessional/<str:id>', views.detailProfessional, name='detailProfessional'),
    path('verif/updateProfessional/<str:id>/<str:status>', views.updateProfessional, name='updateProfessional'),
    path('verif/updateProject/<str:id>', views.updateProject, name='updateProject')
]

user_profile/models.py
from django.db import models

# Create your models here.

user_profile/forms.py
from django import forms    
from django.core.validators import URLValidator

professional_types = [
    ('Architect', 'Architect'), 
    ('Contractor', 'Contractor')
]
structure_types = [
    ('Company','Company'), 
    ('Freelance', 'Freelance')
]
availability_status = [
    ('AVL', 'Available'),
    ('UVL', 'Unavailable')
]
provinces = [
    ('Aceh', 'Aceh'),
    ('Sumatra Utara', 'Sumatra Utara'),
    ('Sumatra Barat', 'Sumatra Barat'),
    ('Riau', 'Riau'),
    ('Kepulauan Riau', 'Kepulauan Riau'),
    ('Jambi', 'Jambi'),
    ('Bengkulu', 'Bengkulu'),
    ('Sumatra Selatan', 'Sumatra Selatan'),
    ('Kepulauan Bangka Belitung', 'Kepulauan Bangka Belitung'),
    ('Lampung', 'Lampung'),
    ('Banten', 'Banten'),
    ('Jawa Barat', 'Jawa Barat'),
    ('DKI Jakarta', 'DKI Jakarta'),
    ('Jawa Tengah', 'Jawa Tengah'),
    ('Daerah Istimewa Yogyakarta', 'Daerah Istimewa Yogyakarta'),
    ('Jawa Timur', 'Jawa Timur'),
    ('Bali', 'Bali'),
    ('Nusa Tenggara Barat', 'Nusa Tenggara Barat'),
    ('Nusa Tenggara Timur', 'Nusa Tenggara Timur'),
    ('Kalimantan Barat', 'Kalimantan Barat'),
    ('Kalimantan Selatan', 'Kalimantan Selatan'),
    ('Kalimantan Tengah', 'Kalimantan Tengah'),
    ('Kalimantan Timur', 'Kalimantan Timur'),
    ('Kalimantan Utara', 'Kalimantan Utara'),
    ('Gorontalo', 'Gorontalo'),
    ('Sulawesi Barat', 'Sulawesi Barat'),
    ('Sulawesi Selatan', 'Sulawesi Selatan'),
    ('Sulawesi Tengah', 'Sulawesi Tengah'),
    ('Sulawesi Tenggara', 'Sulawesi Tenggara'),
    ('Sulawesi Utara', 'Sulawesi Utara'),
    ('Maluku', 'Maluku'),
    ('Maluku Utara', 'Maluku Utara'),
    ('Papua Barat', 'Papua Barat'),
    ('Papua', 'Papua')
]


class OptionalSchemeURLValidator(URLValidator):
    def __call__(self, value):
        if '://' not in value:
            # Validate as if it were http://
            value = 'http://' + value
        super(OptionalSchemeURLValidator, self).__call__(value)
        
class UserProfile(forms.Form):
    name = forms.CharField(widget=forms.TextInput)
    email = forms.EmailField(widget=forms.EmailInput)
    password = forms.CharField(widget=forms.PasswordInput(render_value = True))
    telephone_number = forms.IntegerField()
    profpic = forms.FileField(required=False)
    about_me = forms.CharField(widget=forms.Textarea,required=False )
    status = forms.ChoiceField(choices = availability_status)
    professional_type = forms.ChoiceField(choices = professional_types)
    types = forms.ChoiceField(choices = structure_types)
    city = forms.CharField(widget=forms.TextInput)
    province = forms.ChoiceField(choices = provinces)
    header = forms.FileField(required=False)
    website = forms.CharField(required=False, validators=[OptionalSchemeURLValidator()])
    pic = forms.CharField(widget=forms.TextInput, required=False)
    certification_name = forms.CharField(widget=forms.TextInput, required=False)
    certification_number = forms.CharField(widget=forms.TextInput)
    certification_issued_by = forms.CharField(widget=forms.TextInput, required=False)
    certification_image = forms.FileField(required=False)
    identity_image = forms.FileField(required=False)
    identity_number = forms.CharField(widget=forms.TextInput)
    nib_file = forms.FileField(required=False)

user_profile/views.py
from django.shortcuts import redirect, render
from user_profile.forms import *
from django.core.files.storage import default_storage
from django.core.files.base import ContentFile
from django.db import connection


def login(request):
    if request.session['id'] != '':
        return redirect('user_profile:myProfile')
    if (request.POST):
        email = request.POST['email']
        password = request.POST['password']

        with connection.cursor() as cursor:
            cursor.execute(f"SELECT id FROM BUILDINGO_USER WHERE email='{email}' and password='{password}'")
            user_id = cursor.fetchone()
            
            if(user_id is not None):
                user_id = user_id[0]
                request.session['id'] = user_id

                if user_id[0:2] == 'PO':
                    request.session['role'] = 'Project Owner'
                elif user_id[0:2] == 'PR':
                    request.session['role'] = 'Professional'
                elif user_id[0:2] == 'AD':
                    request.session['role'] = 'Administrator'
                
                return redirect('user_profile:myProfile')

            else:
                alert = {
                    'alert': 'Incorrect email or password.'
                }
                return render(request, 'profile/login.html', alert)

    return render(request, 'profile/login.html')

def logout(request):
    request.session.flush()
    request.session['id'] = ''
    request.session['role'] = ''
    return redirect('home:home')

def signup(request):
    if (request.POST):
        name = request.POST['name']
        email = request.POST['email']
        password = request.POST['password']
        telephone = request.POST['telephone']
        types = request.POST['type']
        city = request.POST['city']
        province = request.POST['province']
        professional_job = request.POST['professional-job']
        professional_type = request.POST['professional-type']

        with connection.cursor() as cursor:
            cursor.execute(f"SELECT id FROM BUILDINGO_USER WHERE id LIKE '{types}%' ")
            list_id = cursor.fetchall()

            max_id = 0
            for type_id in list_id:
                if int(type_id[0][-1]) > max_id:
                    max_id = int(type_id[0][-1])
            
            new_id = f"{types}{max_id + 1}"
            cursor.execute(f"""INSERT INTO BUILDINGO_USER VALUES (
                            '{new_id}', '{name}', '{email}', '{password}', '{telephone}', 'blank.jpg');""")
            
            if types == 'PO':
                cursor.execute(f"""INSERT INTO PROJECT_OWNER(id,city,province) VALUES (
                            '{new_id}', '{city}', '{province}');""")
                request.session['role'] = 'Project Owner'

            elif types =='PR':
                cursor.execute(f"""INSERT INTO PROFESSIONAL(id,city,province,type,professional_type) 
                                VALUES ('{new_id}', '{city}', '{province}','{professional_type}', '{professional_job}');""")
                request.session['role'] = 'Professional'

            request.session['id'] = new_id
                
            return redirect('user_profile:myProfile')

    context = {
        'provinces': provinces
    }
    return render(request, 'profile/signup.html', context)

def getUserData(user):
    return {
        'name': user[1],
        'email': user[2],
        'telephone': user[4],
        'profpic': "/static/profile/images/" + user[5]
    }

def getStatus(acronym):
    if acronym == 'UNV':
        return 'Unverified'
    elif acronym == 'VIP':
        return 'Verification in Progress'
    elif acronym == 'VER':
        return 'Verified'
    elif acronym == 'AVL':
        return 'Available'
    elif acronym == 'UVL':
        return 'Unavailable'

def profile(request):
    if request.session['id'] == '':
        return redirect('user_profile:login')
        
    role = request.session['role']
    if role != 'Project Owner' and role != 'Administrator' and role != 'Professional':
        return redirect('home:home')
    with connection.cursor() as cursor:
        user_id = request.session['id']

        cursor.execute(f"SELECT * FROM BUILDINGO_USER WHERE id='{user_id}'")
        user = list(cursor.fetchone())
        if user[5] is None:
            user[5] = 'blank.jpg'
        context = getUserData(user)

        if role == 'Project Owner':
            cursor.execute(f"SELECT * FROM PROJECT_OWNER WHERE id='{user_id}'")
            additional = cursor.fetchone()
            context['about'] = additional[1]
            context['city'] = additional[2]
            context['province'] = additional[3]

        elif role == 'Professional':
            cursor.execute(f"SELECT * FROM PROFESSIONAL WHERE id='{user_id}'")
            additional = cursor.fetchone()
            context['about'] = additional[1]
            context['status'] = getStatus(additional[2])
            context['professional_type'] = additional[3]
            context['type'] = additional[4]
            context['city'] = additional[5]
            context['province'] = additional[6]
            if additional[7] is not None:
                context['header'] = "/static/profile/images/" + additional[7]
            else:
                context['header'] = "/static/profile/images/blank.jpg"
            context['website'] = additional[8]
            context['pic'] = additional[9]
            context['certification_name'] = additional[10]
            context['certification_number'] = additional[11]
            context['certification_issued_by'] = additional[12]

            if additional[13] is not None:
                context['certification_image'] = "/static/profile/images/" + additional[13]
            else:
                context['certification_image'] = "/static/profile/images/blank.jpg"
            if additional[14] is not None:
                context['identity_image'] = "/static/profile/images/" + additional[14]
            else:
                context['identity_image'] = "/static/profile/images/blank.jpg"
            context['identity_number'] = additional[15]
            if additional[16] is not None:
                context['nib_file'] = "/static/profile/file/" + additional[16]
            else:
                context['nib_file'] = "#"
        
    context["role"] = role
    return render(request, 'profile/profile.html', context)

def profile_outside(request, name):
    with connection.cursor() as cursor:
        cursor.execute(f"SELECT * FROM BUILDINGO_USER WHERE name='{name}'")
        user = list(cursor.fetchone())
        context = getUserData(user)
        context['id'] = user[0]
        
        # Portfolio
        cursor.execute(f"SELECT id,name,city,province FROM PORTFOLIO WHERE professional_id='{user[0]}' LIMIT 3")
        portfolios = cursor.fetchall()

        list_portfolio = [] # [['Title','City','Province', 'URL Link'],...]

        for item in portfolios:
            portfolio = list(item)
            cursor.execute(f"SELECT url FROM IMAGE_PORTFOLIO WHERE portfolio_id='{item[0]}'")
            image = cursor.fetchone()
            if image is not None:
                portfolio.append(image[0])
            list_portfolio.append(portfolio)
        
        context['list_portfolio'] = list_portfolio

        # Profile
        cursor.execute(f"SELECT * FROM PROFESSIONAL WHERE id='{user[0]}'")
        additional = cursor.fetchone()
        context['about'] = additional[1]
        context['status'] = getStatus(additional[2])
        context['professional_type'] = additional[3]
        context['type'] = additional[4]
        context['city'] = additional[5]
        context['province'] = additional[6]
        if additional[7] is not None:
            context['header'] = "/static/profile/images/" + additional[7]
        else:
            context['header'] = "/static/profile/images/blank.jpg"

        context['website'] = additional[8]
        context['pic'] = additional[9]
        context['certification_name'] = additional[10]
        context['certification_number'] = additional[11]
        context['certification_issued_by'] = additional[12]

        if additional[13] is not None:
            context['certification_image'] = "/static/profile/images/" + additional[13]
        else:
            context['certification_image'] = "/static/profile/images/blank.jpg"
    
    context["role"] = request.session['role']
    return render(request, 'profile/profile_outside.html', context)


def edit_profile(request):
    if request.session['id'] == '':
        return redirect('user_profile:login')

    user_id = request.session['id']
    role = request.session['role']
    form = UserProfile()
    
    # Initial value
    with connection.cursor() as cursor:
        
        context = {
            'role': role,
        }

        cursor.execute(f"SELECT * FROM BUILDINGO_USER WHERE id='{user_id}'")
        user = cursor.fetchone()

        form.initial['name'] = user[1]
        form.initial['email'] = user[2]
        form.initial['password'] = user[3]
        form.initial['telephone_number'] = user[4]
        context["profpic"] = "/static/profile/images/" + user[5] 

        if role == 'Project Owner':
            cursor.execute(f"SELECT * FROM PROJECT_OWNER WHERE id='{user_id}'")
            additional = cursor.fetchone()
            form.initial['about_me'] = additional[1]
            form.initial['city'] = additional[2]
            form.initial['province'] = additional[3]

        elif role == 'Professional':
            cursor.execute(f"SELECT * FROM PROFESSIONAL WHERE id='{user_id}'")
            additional = cursor.fetchone()
            form.initial['about_me'] = additional[1]
            form.initial['status'] = getStatus(additional[2])
            form.fields['professional_type'].initial = additional[3]
            form.fields['types'].initial = additional[4]
            form.initial['city'] = additional[5]

user_profile/templates/profile/dashboard.html
{% extends 'home/base.html' %}
{% load static %}

{% block title %}
<title>Dashboard</title>
{% endblock %}

{% block link %}
<link rel="stylesheet" href="{% static 'profile/css/dashboard.css' %}">

{% block style %}
<!-- Specific profile/project/portfolio styling goes here -->
{% endblock %}

{% endblock %}

{% block body %}
<section>
    <h4>Dashboard</h4>
    <div class='dashboard-nav'>
        <div class="dashboard-item">
            <a href="{% url 'user_profile:myProfile' %}" >Profile</a>
        </div>

        {% if role != 'Administrator' %}
        <div class="dashboard-item">
            <a href="{% url 'project:projectList' %}">Project</a>
        </div>
        {% endif %}

        {% if role == 'Administrator' %}
        <div class="dashboard-item">
            <a href="{% url 'verifikasi:listProject' %}">Project List</a>
        </div>
        {% endif %}

        {% if role == 'Professional' %}
        <div class="dashboard-item">
            <a href="{% url 'portfolio:portfolio'%}">Portfolio</a>
        </div>
        {% endif %}

        {% if role == 'Administrator' %}
        <div class="dashboard-item">
            <a href="{% url 'verifikasi:listProfessional' %}">Professional List</a>
        </div>
        {% endif %}
        
    </div>

    <div class="content-wrapper">
        {% block section %}
        {% endblock %}
    </div>
</section>
{% endblock %}

user_profile/templates/profile/login.html
{% extends 'home/base.html' %}
{% load static %}

{% block title %}
<title>Login</title>
{% endblock %}

{% block link %} 
<link rel="stylesheet" href="{% static 'profile/css/login.css' %}">
{% endblock %}

{% block body %}
<section class='d-flex'>
    <div class='login-wrapper'>
        {% if alert %}
        <div class="alert alert-danger" role="alert">
            {{ alert }}
        </div>
        {% else %}
        <div class="alert alert-danger" role="alert" style="visibility:hidden;"></div>
        {% endif %}

        <h3>Log in.</h3>
        <p> Login now to accesss your project or portfolio. </p>
        <form action="{% url 'user_profile:login' %}" method="POST">
          {% csrf_token %}
          <div class="form-group">
            <label for="email">Email address</label>
            <input type="email" class="form-control" id="email" aria-describedby="emailHelp" name='email' required>
          </div>
          <div class="form-group">
            <label for="password">Password</label>
            <input type="password" class="form-control" id="password" name='password' required>
          </div>
          <button type="submit" class="btn submit">Login</button>
        </form>
        <p class='mt-4'>Don't have an account? <a href="{% url 'user_profile:signup' %}">Sign up Now</a></p>
    </div>
    <div class='login-images'>
        <img src="{% static 'profile/images/pexels-pixabay-159045.jpg' %}" class='login-image'>
    </div>
</section>
{% endblock %}

user_profile/templates/profile/profile.html
{% extends 'profile/dashboard.html' %}
{% load static %}

{% block title %}
<title>Profile</title>
{% endblock %}

{% block style %}
<link rel="stylesheet" href="{% static 'profile/css/profile.css' %}">
{% endblock %}

{% block section %}
<div class="profile-wrapper">
    {% if role == 'Professional'%}
    <div class="header">
        <img src="{{ header }}" title="Header" width=100% height='250px' />
    </div>
    {% else %}
    <div class='invisible'>
        
    </div>
    {% endif %}

    {% if status == 'Unverified' %}
    <div class="alert alert-danger" role="alert">
        Attention. Your status is currently Unverified. Your profile won't be seen from Find Professional menu and Project Owner wouldn't be able to find you. Please complete your profile below and request for verification.
    </div>
    {% endif %}
    
    <div class="profile">
        <img src="{{profpic}}" class='profile-picture'>
        <div class="name-type">
            <div class='status-and-name'>
                <p class='name'>{{ name }}</p>
                {% if role == 'Professional'%}
                    {% if status == 'Verified' or status == 'Available' %}
                        <div class='status rounded rounded-pill status-green'>
                    {% elif status == 'Verification in Progress' %}
                        <div class='status rounded rounded-pill status-yellow'>
                    {% else %}
                        <div class='status rounded rounded-pill status-red'>
                    {% endif %}
                    <p class='text-uppercase'> {{status}}</p>
                    </div>
                {% endif %}
            </div>
            
            {% if role == 'Professional'%}
            <p class='text-uppercase professional-type'> {{ professional_type }} </p>
            {% endif %}
        </div>
        
    </div>

    <div class='info-wrapper'>
        <div class='info-content'>
            {% if role == 'Professional' or role == 'Project Owner' %}
            <div class='about card p-3 shadow-sm'>
                <div class='info-title-box'>
                    <p class='sub-title'>ABOUT 
                        {% if type == 'Company' %} US
                        {% else %} ME
                        {% endif %}
                    </p>
                </div>
                <p class='content'>{{about}}</p>
            </div>
            {% endif %}
            <div class='info'>
                <div class='contact card p-3 shadow-sm'>
                    <div class='info-title-box'>
                        <p class='sub-title'>PROFILE DETAIL</p>
                    </div>
                    <div class='d-flex'>
                        <div class='label'> 
                            <p> Email </p>
                            <p> Telephone </p>
                            {% if role == 'Professional' or role == 'Project Owner' %}
                            <p> Location </p>
                            {% endif %}
                            {% if role == 'Professional' %}
                            <p> PIC </p>
                            <p> Website </p>
                            <p> Type </p>
                            {% endif %}
                        </div>
                        <div class='value'>
                            <p> {{ email }} </p>
                            <p> {{ telephone }} </p>
                            {% if role == 'Professional' or role == 'Project Owner' %}
                            <p> {{ city }}, {{ province }} </p>
                            {% endif %}
                            {% if role == 'Professional'%}
                            <p> {{ pic }} </p>
                            <p> {{ website }} </p>
                            <p> {{ type }} </p>
                            {% endif %}
                        </div>
                    </div>
                </div>
                {% if role == 'Professional' %}
                <div class='certificate mt-4 card p-3'>
                    <div class='info-title-box'>
                        <p class='sub-title'>CERTIFICATION DETAIL</p>
                    </div>
                    <div class='d-flex'>
                        <div class='label'> 
                            <p> Name </p>
                            <p> Issued By </p>
                            <p> Number </p>
                            <p> Image </p>
                        </div>
                        <div class='value'>
                            <p> {{ certification_name }} </p>
                            <p> {{ certification_issued_by }} </p>
                            <p> {{ certification_number }} </p>
                            <img src="{{certification_image}}" width=100%>
                        </div>
                    </div>
                </div>
                {% endif %}
            </div>
            
        </div>
        {% if role == 'Professional' %}
        <div class='verification card mt-4 p-3'>
            <div class='info-title-box'>
                <p class='sub-title'>VERIFICATION DETAIL</p>
            </div>
            <div class='d-flex'>
                <div class='label'> 
                    <p> {% if type == 'Company' %} File Nomor Induk Berusaha
                        {% else %} KK
                        {% endif %} 
                    </p>
                    <p> Identity Number ({% if type == 'Company' %}NPWP{% else %}NIK{% endif %}) 
                    </p>
                    <p> {% if type == 'Company' %} NPWP
                        {% else %} KTP
                        {% endif %} Image
                    </p>
                </div>
                <div class='value'>
                    <a href="{{nib_file}}"><i class="fas fa-external-link-alt pdf-file"></i> <span class='open-pdf'>Open File</span> </a>
                    <p> {{ identity_number }} </p>
                    <img src="{{identity_image}}" width=100%>
                    
                </div>
            </div>
        </div>
        {% endif %}

        
    </div>
    {% if status != 'Verification in Progress' %}
    <div class='edit-profile'>
        <button class='btn btn-edit'> <a href="{% url 'user_profile:editProfile' %}">Edit Profile</a></button>
    </div>
    {% endif %}
    {% if status == 'Unverified' %}
    <div class='verify-profile'>
        <button class='btn btn-verify'> <a href="{% url 'user_profile:verifyProfile' %}">Request Verification</a></button>
    </div>
    {% endif %}
        
</div>
{% endblock %}

user_profile/templates/profile/profile_outside.html
{% extends 'home/base.html' %}
{% load static %}

{% block title %}
<title>Profile {{ name }}</title>
{% endblock %}

{% block link %}
<link rel="stylesheet" href="{% static 'profile/css/profile_outside.css' %}">
{% endblock %}

{% block body %}
<div class="profile-wrapper">
    <div class="header">
        <img src="{{header}}" title="Header" width=100% height=250px />
        <div class='profPic'>
            
        </div>
    </div>
    
    <div class="profile">
        <img src="{{profpic}}" class='profile-picture'>
        <div class="name-type">
            <div class='status-and-name'>
                <p class='name'>{{ name }}</p>
                {% if role == 'Professional' %}
                <div class='status rounded rounded-pill'>
                    <p class='text-uppercase'> {{status}}</p>
                </div>
                {% endif %}
            </div>
            <p class='text-uppercase professional-type'> {{ professional_type }} </p>
        </div>
    </div>

    <div class='overview'>
        <p class='sub-title'> OVERVIEW PROJECTS </p>
        <div class='projects'>
            {% for portfolio in list_portfolio %}
            <div class="card">
                <img src="{{ portfolio.4 }}" class="card-img-top" >
                <div class="card-body">
                    <p class='card-location'> {{portfolio.2}}, {{portfolio.3}}</p>
                  <h5 class="card-title">{{portfolio.1}}</h5>
                </div>
            </div>
            {% endfor %}
        </div>
        <p class='interest'>Interested? Request Here or See More Project From This Professional:</p>
        <div class='req-wrapper'>
        <button class='btn req-project'><a href="{% url 'find_professional:projectrequest' id %}">Request Project</a></button>
        <button class='btn req-project'><a href="{% url 'portfolio:portfolioOutside' name %}">See More</a></button>
    </div>
    </div>

    <div class='info-wrapper'>
        <div class='clipped'>

        </div>
        <div class='info-content'>
            <div class='about'>
                <div class='info-title-box'>
                    <p class='sub-title'>ABOUT 
                        {% if type == 'Company' %} US
                        {% else %} ME
                        {% endif %}
                    </p>
                </div>
                <p class='content'>{{about}}</p>
            </div>
            <div class='info'>
                <div class='contact'>
                    <div class='info-title-box'>
                        <p class='sub-title'>PROFILE DETAIL</p>
                    </div>
                    <div class='d-flex'>
                        <div class='label'> 
                            <p> Email </p>
                            <p> Telephone </p>
                            <p> Website </p>
                            <p> Location </p>
                        </div>
                        <div class='value'>
                            <p> {{ email }} </p>
                            <p> {{ telephone }} </p>
                            <p> {{ website }} </p>
                            <p> {{ city }}, {{ province }} </p>
                        </div>
                    </div>
                </div>
                <div class='certificate mt-4'>
                    <div class='info-title-box'>
                        <p class='sub-title'>CERTIFICATION DETAIL</p>
                    </div>
                    <div class='d-flex'>
                        <div class='label'> 
                            <p> Name </p>
                            <p> Issued By </p>
                            <p> Number </p>
                            <p> Photo </p>
                        </div>
                        <div class='value'>
                            <p> {{ certification_name }} </p>
                            <p> {{ certification_issued_by }} </p>
                            <p> {{ certification_number }} </p>
                            <img src="{{certification_image}}" width=100%>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}