buildingo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('', include('user_profile.urls')),
    path('', include('verifikasi.urls')),
    path('', include('find_professional.urls')),
    path('', include('portfolio.urls')),
    path('',include('project.urls'))
]

home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.home, name="home"),
]

verifikasi/urls.py
from django.urls import path
from . import views

app_name = 'verifikasi'

urlpatterns = [
    path('verif/listProfessional', views.listProfessional, name='listProfessional'),
    path('verif/listProject', views.listProject, name='listProject'),
    path('verif/detailProject/<str:id>', views.detailProject, name='detailProject'),
    path('verif/detailProfessional/<str:id>', views.detailProfessional, name='detailProfessional'),
    path('verif/updateProfessional/<str:id>/<str:status>', views.updateProfessional, name='updateProfessional'),
    path('verif/updateProject/<str:id>', views.updateProject, name='updateProject')
]

verifikasi/models.py
from django.db import models

# Create your models here.

verifikasi/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from django.http import HttpResponse, JsonResponse
from django.contrib.sessions.models import Session
from django.db import connection
from django.db.utils import InternalError, IntegrityError
from django.contrib import messages
import datetime

# Create your views here.
def dictfetchall(cursor):
    columns = [col[0] for col in cursor.description]
    return [
        dict(zip(columns, row))
        for row in cursor.fetchall()
    ]

def listProfessional(request):
    role = request.session['role']
    if role == 'Administrator':
        with connection.cursor() as cursor:
            cursor.execute("select * from professional, buildingo_user where professional.id = buildingo_user.id and professional.status = 'VIP'")
            professional = dictfetchall(cursor)
            cursor.execute("select * from professional, buildingo_user, professional_ver where professional.id = professional_ver.id and professional.id = buildingo_user.id and professional.status != 'UNV' and professional.status != 'VIP'")
            verified = dictfetchall(cursor)
            context = {
                'role': role,
                'professional':professional,
                'verified':verified,
            }
        return render(request, 'listProfessional.html', context)

def listProject(request):
    role = request.session['role']
    if role == 'Administrator':
        with connection.cursor() as cursor:
            cursor.execute("select * from cancellation, project where cancellation.project_id = project.id and cancellation.status != 'ACC'")
            project = dictfetchall(cursor)
            cursor.execute("select * from cancellation, project where cancellation.project_id = project.id and cancellation.status = 'ACC'")
            verified = dictfetchall(cursor)
            context = {
                'role': role,
                'project':project,
                'verified':verified,
            }
        return render(request, 'listProject.html', context)

def detailProject(request, id):
    role = request.session['role']
    if role == 'Administrator':
        with connection.cursor() as cursor:
            cursor.execute("select * from cancellation, project, buildingo_user where cancellation.project_id = project.id and buildingo_user.id = project.owner_id and cancellation.status = 'CRQ' and cancellation.project_id=%s",[id])
            row = dictfetchall(cursor)
            cursor.execute("select pic.id_project, buildingo_user.name, professional.professional_type, pic.status from pic, professional, buildingo_user where pic.id_professional = buildingo_user.id and pic.id_professional = professional.id and pic.id_project=%s", [id])
            pic = dictfetchall(cursor)
            cursor.execute("select * from image_project where id=%s", [id])
            gambar = dictfetchall(cursor)
            cursor.execute("select * from file where id=%s", [id])
            dokumen = dictfetchall(cursor)
            context = {
                'role': role,
                'row': row,
                'pic':pic,
                'gambar':gambar,
                'dokumen':dokumen,
            }
        return render(request, 'detailProject.html', context)

def detailProfessional(request, id):
    role = request.session['role']
    if role == 'Administrator':
        with connection.cursor() as cursor:
            cursor.execute("select * from professional inner join buildingo_user using(id) where id=%s", [id])
            row = dictfetchall(cursor)
            for r in row:
                profpic = "/static/profile/images/"+r['profpic']
                certificate = "/static/profile/images/"+r['certification_image']
                identity = "/static/profile/images/"+r['identity_image']
                nib = "/static/profile/file/"+r['nib_file']
            context = {
                'role': role,
                'row': row,
                'profpic':profpic,
                'certificate':certificate,
                'identity':identity,
                'nib':nib,
            }
        return render(request, 'detailProfessional.html', context)

def updateProfessional(request, id, status):
    role = request.session['role']
    if role == 'Administrator':
        admin = request.session['id']
        current_datetime = datetime.date.today()
        with connection.cursor() as cursor:
            cursor.execute("UPDATE professional SET status=%s WHERE id=%s", [status, id])
            if status == 'AVL':
                messages.success(request, "Successful Verification")
                cursor.execute("INSERT INTO professional_ver VALUES(%s, %s, %s)",[id, admin, current_datetime])
            return redirect('verifikasi:listProfessional')

def updateProject(request, id):
    role = request.session['role']
    if role == 'Administrator':
        admin = request.session['id']
        current_datetime = datetime.date.today()
        if request.method == 'POST':
            with connection.cursor() as cursor:
                cursor.execute("UPDATE project SET status='OPN' WHERE id=%s", [id])
                cursor.execute("UPDATE cancellation SET status='ACC' WHERE project_id=%s", [id])
                cursor.execute("UPDATE cancellation SET acc_date=%s WHERE project_id=%s", [current_datetime, id])
                cursor.execute("UPDATE cancellation SET admin_id=%s WHERE project_id=%s", [admin, id])
                cursor.execute("DELETE FROM PIC WHERE id_project=%s", [id])
                messages.success(request, "Project Successfully Canceled")
                return redirect('verifikasi:listProject')

verifikasi/templates/detailProfessional.html
{% extends 'profile/dashboard.html' %}
{% load static %}

{% block title %}
<title>Professional Detail</title>
{% endblock %}

{% block style %}
<link rel="stylesheet" href="{% static 'css/styles.css' %}">
{% endblock %}

{% block section %}
<div class="wrapper">
    <div class="container">
        {%for i in row%}
        <div class="detail shadow-lg">
            <div class="d-flex flex-column align-items-center text-center">
                <img src="{{ profpic }}" alt="" width="150" class="rounded-circle">
                <div class="mt-3">
                    <h4>{{i.name}}</h4>
                    <p class="mb-1">{{i.professional_type}}</p>
                </div>
            </div>
        </div>
        <div class="detail shadow-lg" style="margin-top: 16px;">
            <div style="margin-bottom:35px;">
                <h3 style="color: #463f95;">Profile</h3>
            </div>
            <div class="row">
                <div class="col-sm-3">
                    <h6 class="mb-0">Full Name</h6>
                </div>
                <div class="col-sm-9 text-secondary">
                    {{i.name}}
                </div>
            </div>
            <hr>
            <div class="row">
                <div class="col-sm-3">
                    <h6 class="mb-0">Email</h6>
                </div>
                <div class="col-sm-9 text-secondary">
                    {{i.email}}
                </div>
            </div>
            <hr>
            <div class="row">
                <div class="col-sm-3">
                    <h6 class="mb-0">Phone</h6>
                </div>
                <div class="col-sm-9 text-secondary">
                    {{i.telephone_number}}
                </div>
            </div>
            <hr>
            <div class="row">
                <div class="col-sm-3">
                    <h6 class="mb-0">Professional Type</h6>
                </div>
                <div class="col-sm-9 text-secondary">
                    {{i.professional_type}}
                </div>
            </div>
            <hr>
            <div class="row">
                <div class="col-sm-3">
                    <h6 class="mb-0">Status</h6>
                </div>
                <div class="col-sm-9 text-secondary">
                    {{i.status}}
                </div>
            </div>
            <hr>
            <div class="row">
                <div class="col-sm-3">
                    <h6 class="mb-0">Location</h6>
                </div>
                <div class="col-sm-9 text-secondary">
                    {{i.city}}, {{i.province}}
                </div>
            </div>
            <hr>
            <div class="row">
                <div class="col-sm-3">
                    <h6 class="mb-0">Website</h6>
                </div>
                <div class="col-sm-9 text-secondary">
                    {{i.website}}
                </div>
            </div>
            <hr>
            <div class="row">
                <div class="col-sm-3">
                    <h6 class="mb-0">Certification Number</h6>
                </div>
                <div class="col-sm-9 text-secondary">
                    {{i.certification_number}}
                </div>
            </div>
            <hr>
            <div class="row">
                <div class="col-sm-3">
                    <h6 class="mb-0">Certification Name</h6>
                </div>
                <div class="col-sm-9 text-secondary">
                    {{i.certification_name}}
                </div>
            </div>
            <hr>
            <div class="row">
                <div class="col-sm-3">
                    <h6 class="mb-0">Certification Issued By</h6>
                </div>
                <div class="col-sm-9 text-secondary">
                    {{i.certification_issued_by}}
                </div>
            </div>
            <hr>
            <div class="row">
                <div class="col-sm-3">
                    <h6 class="mb-0">Certificate File</h6>
                </div>
                <div class="col-sm-9 text-secondary">
                    <div class="col-md-6">
                        <div class="col-md-6">
                            <a href="{{ certificate }}"><i class="far fa-file-image"
                                    style="color: rgb(102, 104, 102);"><span style="font-family: Poppins, sans-serif;">
                                        certificate_image</span></i></a>
                        </div>
                    </div>
                </div>
            </div>
            <hr>
            <div class="row">
                <div class="col-sm-3">
                    <h6 class="mb-0">Identity Number</h6>
                </div>
                <div class="col-sm-9 text-secondary">
                    {{i.identity_number}}
                </div>
            </div>
            <hr>
            <div class="row">
                <div class="col-sm-3">
                    <h6 class="mb-0">Identity File</h6>
                </div>
                <div class="col-sm-9 text-secondary">
                    <div class="col-md-6">
                        <div class="col-md-6">
                            <a href="{{ identity }}"><i class="far fa-file-image"
                                    style="color: rgb(102, 104, 102);"><span style="font-family: Poppins, sans-serif;">
                                        identity_image</span></i></a>
                        </div>
                    </div>
                </div>
            </div>
            <hr>
            <div class="row">
                <div class="col-sm-3">
                    <h6 class="mb-0">NIB File</h6>
                </div>
                <div class="col-sm-9 text-secondary">
                    <div class="col-md-6">
                        <div class="col-md-6">
                            <a href="{{ nib }}"><i class="far fa-file-pdf" style="color: rgb(102, 104, 102);"><span
                                        style="font-family: Poppins, sans-serif;">
                                        nib_file</span></i></a>
                        </div>
                    </div>
                </div>
            </div>
            <hr>
            <div class="row">
                <div class="col-sm-3">
                    <h6 class="mb-0">Person In Charge</h6>
                </div>
                <div class="col-sm-9 text-secondary">
                    {{i.person_in_charge}}
                </div>
            </div>
            <hr>
            <div style="margin-top:35px; text-align: center;">
                <a href="{% url 'verifikasi:updateProfessional' id=i.id status='AVL'%}" class="btn btn-success"
                    style="font-size: 1.2em;">verified</a>
                <a href="{% url 'verifikasi:updateProfessional' id=i.id status='UNV'%}" class="btn btn-danger"
                    style="font-size: 1.2em;">unverified</a>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

verifikasi/templates/detailProject.html
{% extends 'profile/dashboard.html' %}
{% load static %}

{% block title %}
<title>Project Detail</title>
{% endblock %}

{% block style %}
<link rel="stylesheet" href="{% static 'css/styles.css' %}">
{% endblock %}

{% block section %}
<div class="wrapper">
    <div class="container">
        {%for i in row%}
        <form action="{% url 'verifikasi:updateProject' id=i.project_id %}" method="POST">
            {% csrf_token %}
            <div class="detail shadow-lg">
                <div style="margin-bottom:35px;">
                    <h3 style="color: #463f95;">Project Detail</h3>
                </div>
                <div class="row">
                    <div class="col-sm-3">
                        <h6 class="mb-0">Project Name</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                        {{i.title}}
                    </div>
                </div>
                <hr>
                <div class="row">
                    <div class="col-sm-3">
                        <h6 class="mb-0">Project Owner</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                        {{i.name}}
                    </div>
                </div>
                <hr>
                <div class="row">
                    <div class="col-sm-3">
                        <h6 class="mb-0">Status</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                        {{i.status}}
                    </div>
                </div>
                <hr>
                <div class="row">
                    <div class="col-sm-3">
                        <h6 class="mb-0">Estimated Time</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                        {{i.estimated_time}}
                    </div>
                </div>
                <hr>
                <div class="row">
                    <div class="col-sm-3">
                        <h6 class="mb-0">Budget Range</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                        {{i.budget_range}}
                    </div>
                </div>
                <hr>
                <div class="row">
                    <div class="col-sm-3">
                        <h6 class="mb-0">Additional Data</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                        {% for f in dokumen %}
                        <div class="col-md-6">
                            <a href="{% static f.url %}"><i class="far fa-file-pdf"
                                    style="color: rgb(102, 104, 102);"><span style="font-family: Poppins, sans-serif;">
                                        Additional_Data.pdf</span></i></a>
                        </div>
                        {% endfor %}
                    </div>
                </div>
                <hr>
                <div style="margin-bottom:35px; margin-top:35px;">
                    <h3 style="color: #463f95;">Building Preference</h3>
                </div>
                <div class="row">
                    <div class="col-sm-3">
                        <h6 class="mb-0">Building Type</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                        {{i.building_type}}
                    </div>
                </div>
                <hr>
                <div class="row">
                    <div class="col-sm-3">
                        <h6 class="mb-0">Project Type</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                        {{i.type}}
                    </div>
                </div>
                <hr>
                <div class="row">
                    <div class="col-sm-3">
                        <h6 class="mb-0">Style Preference</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                        {{i.building_style}}
                    </div>
                </div>
                <hr>
                <div class="row">
                    <div class="col-sm-3">
                        <h6 class="mb-0">Location</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                        {{i.city}}, {{i.province}}
                    </div>
                </div>
                <hr>
                <div class="row">
                    <div class="col-sm-3">
                        <h6 class="mb-0">Widht Area</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                        {{i.width}}
                    </div>
                </div>
                <hr>
                <div class="row">
                    <div class="col-sm-3">
                        <h6 class="mb-0">Long Area</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                        {{i.length}}
                    </div>
                </div>
                <hr>
                <div class="row">
                    <div class="col-sm-3">
                        <h6 class="mb-0">Wants</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                        {{i.wants}}
                    </div>
                </div>
                <hr>
                <div class="row">
                    <div class="col-sm-3">
                        <h6 class="mb-0">Needs</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                        {{i.needs}}
                    </div>
                </div>
                <hr>
                <div class="row">
                    <div class="col-sm-3">
                        <h6 class="mb-0">Image</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                        {% for image in gambar %}
                        <div class="col-md-6">
                            <a href="{% static image.url %}"><i class="far fa-file-image"
                                    style="color: rgb(102, 104, 102);"><span style="font-family: Poppins, sans-serif;">
                                        Image.png</span></i></a>
                        </div>
                        {% endfor %}
                    </div>
                </div>
                <hr>
            </div>
            <div class="detail shadow-lg" style="margin-top: 16px;">
                <div style="margin-bottom:35px;">
                    <h3 style="color: #463f95;">Professional in Charge</h3>
                </div>
                {% for a in pic %}
                <div class="row">
                    <div class="col-sm-3">
                        <h6 class="mb-0">{{a.professional_type}}</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                        {{a.name}} ({{a.status}})
                    </div>
                </div>
                <hr>
                {% endfor %}
                <div class="row">
                    <div class="col-sm-3">
                        <h6 class="mb-0">Invoice</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                        <div class="col-md-6">
                            -
                        </div>
                    </div>
                </div>
                <hr>
                <div class="row">
                    <div class="col-sm-3">
                        <h6 class="mb-0">Output</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                        <div class="col-md-6">
                            -
                        </div>
                    </div>
                </div>
                <hr>
                <div class="row">
                    <div class="col-sm-3">
                        <h6 class="mb-0">Reason for Cancellation</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                        {{i.reason}}
                    </div>
                </div>
                <hr>
                <div style="margin-top:35px; text-align: center;">
                    <button type="submit" class="btn btn-success">accept</button>
                </div>
            </div>
        </form>
        {%endfor%}
    </div>
</div>
{% endblock %}

verifikasi/templates/listProfessional.html
{% extends 'profile/dashboard.html' %}
{% load static %}

{% block title %}
<title>List Professional</title>
{% endblock %}

{% block style %}
<link rel="stylesheet" href="{% static 'css/styles.css' %}">
<link rel="stylesheet" href="{% static 'css/list.css' %}">
{% endblock %}

{% block section %}
<div class="wrapper">
    <div class="container">
        {% for msg in messages %}
        <div class="alert alert-success alert-dismissible fade show" role="alert">
            <h6>{{msg}}</h6>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        {% endfor %}
        <h2 class="container-header">Professional List</h2>
        <div class="list-item" id="todos">
            {%for i in professional%}
            <div class="item shadow-lg">
                <div class="p-2 bd-highlight">
                    <i class="fas fa-user fa-3x"></i>
                </div>
                <div class="p-2 flex-grow-1 bd-highlight">
                    <div class="inner">
                        <h2>{{i.name}}</h2>
                        <p>{{i.professional_type}}</p>
                    </div>
                </div>
                <div class="p-2 bd-highlight">
                    <a class="btn-detail btn" href="{% url 'verifikasi:detailProfessional' id=i.id %}">Detail</a>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
    <div class="container">
        <h2 class="container-header">Verified List</h2>
        <div class="list-item" id="todos">
            {%for j in verified%}
            <div class="item shadow-lg">
                <div class="p-2 bd-highlight">
                    <i class="fas fa-user-check fa-3x"></i>
                </div>
                <div class="p-2 flex-grow-1 bd-highlight">
                    <div class="inner">
                        <h2>{{j.name}}</h2>
                        <p>{{j.professional_type}}</p>
                    </div>
                </div>
                <div class="p-2 bd-highlight">
                    <div class="inner">
                        <p>{{j.ver_date}}</p>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

verifikasi/templates/listProject.html
{% extends 'profile/dashboard.html' %}
{% load static %}

{% block title %}
<title>List Project</title>
{% endblock %}

{% block style %}
<link rel="stylesheet" href="{% static 'css/styles.css' %}">
<link rel="stylesheet" href="{% static 'css/list.css' %}">
{% endblock %}

{% block section %}
<div class="wrapper">
    <div class="container">
        {% for msg in messages %}
        <div class="alert alert-success alert-dismissible fade show" role="alert">
            <h6>{{msg}}</h6>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        {% endfor %}
        <h2 class="container-header">Project List</h2>
        <div class="list-item" id="todos">
            {%for i in project%}
            <div class="item shadow-lg">
                <div class="p-2 bd-highlight">
                    <i class="fas fa-building fa-3x"></i>
                </div>
                <div class="p-2 flex-grow-1 bd-highlight">
                    <div class="inner">
                        <h2>{{i.title}}</h2>
                        <p>{{i.type}}</p>
                    </div>
                </div>
                <div class="p-2 bd-highlight">
                    <a class="btn-detail btn" href="{% url 'verifikasi:detailProject' id=i.project_id %}">Detail</a>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
    <div class="container">
        <h2 class="container-header">Cancellation Accepted</h2>
        <div class="list-item" id="todos">
            {%for j in verified%}
            <div class="item shadow-lg">
                <div class="p-2 bd-highlight">
                    <i class="fas fa-check fa-3x"></i>
                </div>
                <div class="p-2 flex-grow-1 bd-highlight">
                    <div class="inner">
                        <h2>{{j.title}}</h2>
                        <p>{{j.type}}</p>
                    </div>
                </div>
                <div class="p-2 bd-highlight">
                    <div class="inner">
                        <p>{{j.acc_date}}</p>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}